{{- if .Values.argoRollouts.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout
  namespace: openshift-gitops
spec:
  extraCommandArgs:
    - '--namespaced=false'
{{ end }}
