apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: shop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: products-umbrella
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: productsNetworkingOnline-0.1.0
  name: products-umbrella-online-prometheus-monitor
  namespace: gitops
spec:
  endpoints:
    - interval: 30s
      path: /q/metrics
      scheme: http
      targetPort: 8080
  selector:
    matchLabels:
      app.kubernetes.io/instance: shop
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: products-umbrella
      app.kubernetes.io/version: 1.0.0
      helm.sh/chart: productsNetworkingOnline-0.1.0

